# Generated by Django 5.1.1 on 2024-10-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comets',
            fields=[
                ('obj_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('p_ir', models.FloatField()),
                ('moid_au', models.FloatField()),
                ('w_deg', models.FloatField()),
                ('ref', models.CharField(max_length=100)),
            ],
        ),
    ]
